### PR TITLE
V0.1.1

### PR DESCRIPTION
**Pull request by tusharchou**
**Name**: Milestone 0.1.1 release 
**About**: Fixing minor issues and 0.1.1 release
**Title**: Milestone 0.1.1 release

Is your pull request related to a issue? Please tag.
No 

Describe the solution you have implemented
Some minor bugs fixed 

Describe why alternatives you considered are not optimal

Additional context
Check milestone 0.1.1 for all features including in this release

### CODE REVIEW

**Comment by mrutunjay-kinagi** [comment]
@tusharchou  : Can we get over a call for Quick Code Review ?

**Comment by redpheonixx** [comment]
> @tusharchou : Can we get over a call for Quick Code Review ?

include me also in that call

**Comment by tusharchou** [comment]
@mrutunjay-kinagi @redpheonixx let me buy you both a coffee ☕ 
https://calendly.com/tushar-choudhary-de/30min

**Comment by redpheonixx** [comment]
> @mrutunjay-kinagi @redpheonixx let me buy you both a coffee ☕ https://calendly.com/tushar-choudhary-de/30min

scheduling call at 6:30 pm as per slot available if okay with @tusharchou @mrutunjay-kinagi

**Review by redpheonixx — APPROVED** [review]
As discussed will run this locally today night. Approving for now.

**Pull request merged**
