### PR TITLE
0.1.1 BigQuery Release 

### PR DESCRIPTION
**Pull request by tusharchou**
Create publish.yml for PYPI package release 

To automate the release of your Python package to PyPI through GitHub, you can use GitHub Actions1
. Here’s a step-by-step guide to set it up:

Create a PyPI API Token:

Go to your PyPI account settings and generate an API token2
.

Copy the token for later use2
.

Add the API Token to GitHub Secrets:

Go to your GitHub repository settings2
.

Navigate to Secrets and add a new repository secret named PYPI_API_TOKEN2
.

Paste your PyPI API token into the value field2
.

Create a GitHub Workflow File:

In your repository, create a new file at .github/workflows/release_to_pypi.yml2
.

Add the following content to the file:

### CODE REVIEW

**Comment by mrutunjay-kinagi** [comment]
@tusharchou : Lets tag this a release branch with tags. Lets create a release branch with version tag from main and have this github action setup done only for the release branch. 

@abhishekkar0603 , @redpheonixx  : What do you think  ?

**Comment by tusharchou** [comment]
#38 Let me attempt to close this issue with this PR

**Review by mrutunjay-kinagi — APPROVED** [review]
This is a great start ! 🚀

**Review by rakhioza07 — APPROVED** [review]
LGTM!

**Pull request merged**
