### PR TITLE
0.1.2 Testing pre release for 0.1.1

### PR DESCRIPTION
**Pull request by tusharchou**
# Local Data Warehousing
> To use duckdb, a python based query engine, to query iceberg tables locally by using domain.transaction

## Journey So Far
In the first release of local-data-platform 0.1.0 we had lauched helloworld. From that in the last sprint we have come far by implemting a google cloud service called BigQuery as source and writting data in a target iceberg table

## Issues To-do

- [ ] #33 Fixing the docs on read the docs
- [ ] #33 .README.md
- [ ] #33 doc strings
- [ ] #5 Test 0.1.1 pre release
- [ ] #17 pypi release notes and read me
- [ ] #4 Near Lake house integration Demo
- [ ] #3 Local Warehouse Integration

## Feature To Build

> Ability to query local lakehouse using duckdb

### CODE REVIEW

**Review by mrutunjay-kinagi — COMMENTED** [review]
Are these changes for Read the Docs ? I'm asking this because branch name got me confused.

**Comment by tusharchou** [comment]
Yes I have linked multiple issues in this PR managing one branch per issue is not working out though all issues have this branch linked. I ll make the branch naming better thanks for pointing that out.

**Comment by mrutunjay-kinagi** [comment]
> Yes I have linked multiple issues in this PR managing one branch per issue is not working out though all issues have this branch linked. I ll make the branch naming better thanks for pointing that out.

@tusharchou  : Okay. I'll merge this pull request. By the way, we need to come up with PR / Issue templates so that we can be consistent. These can evolve over time.

**Review by mrutunjay-kinagi — APPROVED** [review]

**Comment by mrutunjay-kinagi** [comment]
@tusharchou : We should make a habit of squash merge to keep a linear project history.

**Comment by tusharchou** [comment]
@mrutunjay-kinagi please wait for all the issues to resolve before reviewing and merging

**Pull request merged**
